name:                template
version:             1.0.0
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2019 Jappie Klooster"

extra-source-files:
- Readme.md
- LICENSE

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

# from https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
default-extensions:
  # trivial
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # only activated once used
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # no cost deriving power
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # used everywhere anyway
  - OverloadedStrings
  # ehh syntax
  - TypeApplications

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  exe:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - template
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
